package com.doukyo.user

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table

// A JPA ENTITY: this class maps to a database table. One instance = one row.
//
// Note it is a regular `class`, NOT a `data class`. Data classes derive
// equals/hashCode/copy from all properties, which breaks JPA identity (entities
// should be equal by id) and corrupts hash-based collections when mutable fields
// change. Entities are always plain classes.
//
// The `kotlin("plugin.jpa")` build plugin generates the no-arg constructor
// Hibernate needs to build instances via reflection.
@Entity
@Table(name = "users")   // maps to the `users` table (`user` is a SQL reserved word)
class User(

    @Column(nullable = false)
    var name: String,

    @Column(nullable = false, unique = true)
    var email: String,

    // The primary key. IDENTITY = the DATABASE assigns the value on insert
    // (matches `id BIGINT GENERATED BY DEFAULT AS IDENTITY` in V1__init.sql).
    // Nullable with a default of null because a brand-new, unsaved User has no id
    // yet — the DB fills it in when save() runs.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,
)
