-- V1: foundation schema (design doc §6.1).
-- Household <-> User is MANY-TO-MANY, expressed through the `memberships` join table.
-- Flyway runs this exactly once and records it in flyway_schema_history.

-- A person. Email is unique so one account maps to one email.
CREATE TABLE users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE          -- 320 = max valid email length
);

-- A shared house (the tenant boundary; everything else will belong to one).
CREATE TABLE households (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()   -- timestamptz = instant in UTC
);

-- The JOIN TABLE linking users to households. Its two foreign keys ARE the
-- many-to-many relationship made concrete (design doc §6.1).
CREATE TABLE memberships (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
    household_id BIGINT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    joined_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- A user can belong to a given household at most once.
    CONSTRAINT uq_membership_user_household UNIQUE (user_id, household_id)
);

-- PostgreSQL does NOT auto-index foreign keys. These indexes make the two hot
-- questions fast: "who is in this household?" and "what households is this user in?"
CREATE INDEX idx_memberships_household ON memberships (household_id);
CREATE INDEX idx_memberships_user      ON memberships (user_id);
