-- V2: expenses & splitting (design doc §6.2).
-- One expense, MANY shares (one-to-many). Shares always sum to the expense amount
-- — an aggregate invariant enforced in the application within one transaction,
-- because Postgres CHECK constraints see a single row and can't express a
-- cross-row SUM without a trigger.

CREATE TABLE expenses (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT       NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    -- RESTRICT: you cannot delete a user who has financial history (never silently
    -- erase money records — removing such a member must be handled explicitly).
    paid_by      BIGINT       NOT NULL REFERENCES users(id)      ON DELETE RESTRICT,
    description  VARCHAR(255) NOT NULL,
    -- Money as INTEGER CENTS (never floating point): $84.00 is 8400. Exact
    -- arithmetic; the UI converts to dollars only for display.
    amount_cents BIGINT       NOT NULL CHECK (amount_cents > 0),
    category     VARCHAR(32)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE expense_shares (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- CASCADE: a share is OWNED by its expense — delete the expense, delete its
    -- shares. (The Expense is the aggregate root; shares have no life of their own.)
    expense_id   BIGINT  NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    user_id      BIGINT  NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
    amount_cents BIGINT  NOT NULL CHECK (amount_cents >= 0),
    is_paid      BOOLEAN NOT NULL DEFAULT false,
    -- One share per user per expense.
    CONSTRAINT uq_share_expense_user UNIQUE (expense_id, user_id)
);

CREATE INDEX idx_expenses_household ON expenses (household_id);
CREATE INDEX idx_shares_expense     ON expense_shares (expense_id);
-- PARTIAL index: the "who owes what" query filters unpaid shares. Once debts
-- settle, unpaid rows are a small fraction — so index only those.
CREATE INDEX idx_shares_user_unpaid ON expense_shares (user_id) WHERE is_paid = false;
