-- V2: authentication — password credentials + refresh tokens.
-- Extends `users` with a password hash (NULLABLE: external-only accounts have no
-- password) and an email-verified flag; adds refresh_tokens for revocable sessions.

ALTER TABLE users ADD COLUMN password_hash  VARCHAR(255);
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE refresh_tokens (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- We store a HASH of the token, never the token itself — same principle as
    -- passwords. A leaked DB row can't be replayed as a valid token.
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ  NOT NULL,
    revoked_at TIMESTAMPTZ,                    -- set on rotation/logout; NULL = active
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_refresh_user ON refresh_tokens (user_id);
