CREATE TABLE oauth_accounts (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(255) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    -- One external identity maps to at most one Doukyo user (also indexes the
    -- (provider, provider_user_id) lookup used on every OAuth sign-in).
    CONSTRAINT uq_oauth_provider_user UNIQUE (provider, provider_user_id)
);

-- Postgres does not auto-index foreign keys. This is what makes "does this user
-- already have a linked account?" and the ON DELETE CASCADE cleanup efficient.
CREATE INDEX idx_oauth_accounts_user ON oauth_accounts (user_id);