-- Household chat. There is no chat roster: membership in the household IS
-- membership in the conversation (see the chat design doc, D2).

CREATE TABLE messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    sender_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body         TEXT NOT NULL,
    -- Client-generated id: makes a retried send idempotent, and lets the sender
    -- match the server echo to its optimistic bubble.
    client_id    VARCHAR(64) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_messages_household_client UNIQUE (household_id, client_id)
);

-- The only hot read: "latest N in this household", and keyset paging back from a
-- cursor. A descending composite index serves both.
CREATE INDEX idx_messages_household_id ON messages (household_id, id DESC);
CREATE INDEX idx_messages_sender ON messages (sender_id);

-- One bookmark per person per household, for unread counts.
CREATE TABLE message_reads (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    household_id         BIGINT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    last_read_message_id BIGINT NOT NULL DEFAULT 0,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_message_reads_user_household UNIQUE (user_id, household_id)
);

CREATE INDEX idx_message_reads_household ON message_reads (household_id);
