-- Email verification for password sign-ups.
--
-- The user row is NOT created until the code comes back. Creating it up front
-- with email_verified = false would let anyone squat on an address they don't
-- own: the unverified row holds the email, and the real owner can never sign up.
-- That is the same hole the old createUser mutation had.
--
-- So `users` only ever contains accounts someone has proven they can receive
-- mail for, and everything in flight lives here instead.
CREATE TABLE pending_signups (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    -- Already bcrypt-hashed; the plaintext never reaches this table.
    password_hash VARCHAR(255) NOT NULL,
    -- SHA-256 of the code. Hygiene, not a security boundary: six digits fall to
    -- a brute force in under a second offline. The attempt counter below is what
    -- actually protects it.
    code_hash     VARCHAR(255) NOT NULL,
    attempts      INT          NOT NULL DEFAULT 0,
    expires_at    TIMESTAMPTZ  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- One live code per address. Requesting again replaces the row, so an
    -- attacker cannot accumulate valid codes and try them in parallel.
    CONSTRAINT uq_pending_signups_email UNIQUE (email)
);
